### ISSUE TITLE
REJECT POSITION CONTROL, EKF2 STATUS Local Position: Invalid

### ISSUE THREAD

**Issue by gyronikeleg** [PX4/PX4-Autopilot#13510]
I created my own motion capture system, am I able to position the drone and send posa data via Matlab ROS integration and get the correct output when I echo the vision_pose topic in MAVROS from the Onboard Computer.  

**When I switch to Position Control on my Taranis I get a "Reject Position Control" result from QGC**

**Mavlink Console also says the following for EKF2 Status:**
![Capture](https://user-images.githubusercontent.com/49045956/69107103-4f207a00-0a3e-11ea-84f1-9183851883ee.PNG)

Here is my flight log:
https://logs.px4.io/plot_app?log=c33ff996-c4ae-4558-b844-6205f4c976e8

**I am only able to send position data at ~5 hz, is this the cause of the problem?**

**Comment by julianoes** [comment]
@kamilritz do you see what is going on?

**Comment by kamilritz** [comment]
@gyronikeleg 
As far as I know, the vision_pose topic is only consumed by the Local Position Estimator (LPE) and not by the EKF2 module. So I would argue that your pose information never reached the estimator and therefore you had no local position.

Is your motion capture system publishing a 6DOF pose? I never worked with Matlab ROS integration. Are you using MAVROS to communicate with the vehicle?

**Comment by gyronikeleg** [comment]
> @gyronikeleg
> As far as I know, the vision_pose topic is only consumed by the Local Position Estimator (LPE) and not by the EKF2 module. So I would argue that your pose information never reached the estimator and therefore you had no local position.
>
Is there a way I can confirm this?

> Is your motion capture system publishing a 6DOF pose? I never worked with Matlab ROS integration. Are you using MAVROS to communicate with the vehicle?

Yes, I'm using MAVROS and publishing the 6DOF pose from MATLAB.  When I echo the vision pose topic in MAVROS, I get the correct pose information.

**Comment by kamilritz** [comment]
@gyronikeleg I would use the `ODOMETRY` plugin of MAVROS. So publishing on the /mavros/odometry/out topic. Is your MOCAP system also computing velocities? If yes, this can help the drone with higher performance. If no, you can set the velocity components of the `nav_msgs/Odometry` probably to NAN or zero. 
A way to check if the odometry is received then on the Firmware side is to temporally set MAV_ODOM_LP=1 and MAV_0_MODE to "external vision min". After setting this, you can check the incoming and from MAVROS transformed MOCAP data under the `ODOMETRY` topic with the MAVLink inspector of QGroundcontrol. 
On the Firmwareside you should set the `EV_POS`, `EV_YAW` (and `EV_VEL`) bits of the  EKF2_AID_MASK parameter to true and EKF2_HGT_MODE to `vision` in order to fuse the information in the EKF.

**Comment by gyronikeleg** [comment]
@kamilritz 
> @gyronikeleg I would use the ODOMETRY plugin of MAVROS. So publishing on the /mavros/odometry/out topic.

**Done. in matlab I published as follows:**
```
rosinit('192.168.1.14');
robotVision = rospublisher('/mavros/odometry/out','geometry_msgs/PoseStamped');
posemsg = rosmessage(robotVision);

tic
mRate = 50;
while true
    elapsedTime = toc;
    if(elapsedTime>=(1/mRate))
        posemsg.Pose.Position.X = 0;
        posemsg.Pose.Position.Y = 0;
        posemsg.Pose.Position.Z = 0;
        posemsg.Pose.Orientation.X = 0;
        posemsg.Pose.Orientation.Y = 0;
        posemsg.Pose.Orientation.Z = 0;
        posemsg.Pose.Orientation.W = 1;
        posemsg.Header.Stamp = rostime("now");
        posemsg.Header.FrameId = 'World';
        send(robotVision,posemsg);
        tic
    end
end

````
> Is your MOCAP system also computing velocities? If yes, this can help the drone to achieve higher flight performance. If no, you can set the velocity components of the nav_msgs/Odometry probably to NAN or zero and tell the FCU not to use it.

**My MOCAP systems does not compute velocities.  How do I set the velocities to zero? (sorry a bit new to this)**

> A way to check if the odometry is received then on the Firmware side is to temporally set MAV_ODOM_LP=1 and MAV_0_MODE to "external vision min". After setting this, you can check the incoming and from MAVROS transformed MOCAP data under the ODOMETRY topic with the MAVLink inspector of QGroundcontrol.

**I attached a picture of the mavlink inspector.  The numbers in mavlink inspector don't match what I am publishing.**
![mavlink_inspector](https://user-images.githubusercontent.com/49045956/69287467-67220600-0bc4-11ea-929b-69ca55a6ec36.PNG)

**I am publishing exact numbers:
x=0,y=0,z=0
x=0,y=0,z=0,w=1
^these are shown as exact in Mavros**

> On the Firmware side you should set the EV_POS, EV_YAW (and EV_VEL) bits of the EKF2_AID_MASK parameter to true and EKF2_HGT_MODE to vision in order to fuse the information in the EKF.

**Done, I set EKF2_AID_MASK to 24 in QGC**

**Still getting the reject position error**

**Comment by kamilritz** [comment]
> Done. in matlab I published as follows:

You are not sending the the pose information to MAVROS correctly. MAVROS expects a message of type [nav_msgs/Odometry](http://docs.ros.org/melodic/api/nav_msgs/html/msg/Odometry.html). You can check this by listening to the /mavros/odometry/out topic. If you are not that familiar with ROS [this](http://wiki.ros.org/ROS/Tutorials/UnderstandingTopics) should help you how to check that you are sending your data on the right topic.

How do you launch MAVROS? And are you sure the connection to the FCU is detected?

**Comment by gyronikeleg** [comment]
**I updated the odometry to use the correct message type:**
````
rosshutdown
rosinit('192.168.1.14');
robotVision = rospublisher('/mavros/odometry/out','nav_msgs/Odometry');
posemsg = rosmessage(robotVision);

tic
mRate = 50;
while true
    elapsedTime = toc;
    if(elapsedTime>=(1/mRate))
        posemsg.Pose.Pose.Position.X = 0;
        posemsg.Pose.Pose.Position.Y = 0;
        posemsg.Pose.Pose.Position.Z = 0;
        posemsg.Pose.Pose.Orientation.X = 0;
        posemsg.Pose.Pose.Orientation.Y = 0;
        posemsg.Pose.Pose.Orientation.Z = 0;

        posemsg.Header.Stamp = rostime("now");
        posemsg.Header.FrameId = 'odom';
        send(robotVision,posemsg);
        tic
    end
end
````

**I tried to do the rqt_graph but I get this error.  The plugin is installed, so not sure why I get the error**

rqt_graph: cannot connect to X server

**Here are the diagnostics output, I do get a heartbeat**
**I launch mavros from putty terminal with this command:**
roslaunch mavros px4.launch fcu_url:=serial:///dev/ttyUSB0:921600 gcs_url:=udp://@192.168.1.2:14550


```
`header:
  seq: 407
  stamp:
    secs: 1574379486
    nsecs: 304382671
  frame_id: ''
status:
  -
    level: 0
    name: mavros: FCU connection
    message: connected
    hardware_id: serial:///dev/ttyUSB0:921600
    values:
      -
        key: Received packets:
        value: 45872
      -
        key: Dropped packets:
        value: 0
      -
        key: Buffer overruns:
        value: 0
      -
        key: Parse errors:
        value: 0
      -
        key: Rx sequence number:
        value: 125
      -
        key: Tx sequence number:
        value: 57
      -
        key: Rx total bytes:
        value: 7258161
      -
        key: Tx total bytes:
        value: 272492
      -
        key: Rx speed:
        value: 14560.000000
      -
        key: Tx speed:
        value: 517.000000
  -
    level: 0
    name: mavros: GCS bridge
    message: connected
    hardware_id: serial:///dev/ttyUSB0:921600
    values:
      -
        key: Received packets:
        value: 20
      -
        key: Dropped packets:
        value: 0
      -
        key: Buffer overruns:
        value: 0
      -
        key: Parse errors:
        value: 0
      -
        key: Rx sequence number:
        value: 19
      -
        key: Tx sequence number:
        value: 0
      -
        key: Rx total bytes:
        value: 24541
      -
        key: Tx total bytes:
        value: 7257875
      -
        key: Rx speed:
        value: 47.000000
      -
        key: Tx speed:
        value: 14526.000000
  -
    level: 2
    name: mavros: GPS
    message: No satellites
    hardware_id: serial:///dev/ttyUSB0:921600
    values:
      -
        key: Satellites visible
        value: 0
      -
        key: Fix type
        value: 0
      -
        key: EPH (m)
        value: 99.99
      -
        key: EPV (m)
        value: 99.99
  -
    level: 0
    name: mavros: Heartbeat
    message: Normal
    hardware_id: serial:///dev/ttyUSB0:921600
    values:
      -
        key: Heartbeats since startup
        value: 526
      -
        key: Frequency (Hz)
        value: 1.036986
      -
        key: Vehicle type
        value: Quadrotor
      -
        key: Autopilot type
        value: PX4
      -
        key: Mode
        value: ALTCTL
      -
        key: System status
        value: Standby
  -
    level: 0
    name: mavros: System
    message: Normal
    hardware_id: serial:///dev/ttyUSB0:921600
    values:
      -
        key: Sensor present
        value: 0x002F002F
      -
        key: Sensor enabled
        value: 0x0021000F
      -
        key: Sensor helth
        value: 0x002F000F
      -
        key: Sensor 3D Gyro
        value: Ok
      -
        key: Sensor 3D Accel
        value: Ok
      -
        key: Sensor 3D Mag
        value: Ok
      -
        key: Sensor Abs Pressure
        value: Ok
      -
        key: Sensor RC Receiver
        value: Ok
      -
        key: AHRS health
        value: Ok
      -
        key: CPU Load (%)
        value: 52.1
      -
        key: Drop rate (%)
        value: 0.0
      -
        key: Errors comm
        value: 0
      -
        key: Errors count #1
        value: 0
      -
        key: Errors count #2
        value: 0
      -
        key: Errors count #3
        value: 0
      -
        key: Errors count #4
        value: 0
  -
    level: 0
    name: mavros: Battery
    message: Normal
    hardware_id: serial:///dev/ttyUSB0:921600
    values:
      -
        key: Voltage
        value: 10.94
      -
        key: Current
        value: 0.3
      -
        key: Remaining
        value: 28.0
  -
    level: 0
    name: mavros: Time Sync
    message: Normal
    hardware_id: serial:///dev/ttyUSB0:921600
    values:
      -
        key: Timesyncs since startup
        value: 850
      -
        key: Frequency (Hz)
        value: 9.999511
      -
        key: Last dt (ms)
        value: 0.175010
      -
        key: Mean dt (ms)
        value: 0.001993
      -
        key: Last system time (s)
        value: 988.079634000
      -
        key: Time offset (s)
        value: 1574378498.134831667

````
