### ISSUE TITLE
ulanding_radar module start bug

### ISSUE THREAD

**Issue by harrisonmg** [PX4/PX4-Autopilot#18516]
I have an Ainstein (Aerotenna) radar, and noticed the driver was not starting correctly on init.

The issue was fixed by changing `ulanding_radar/module.yaml` from
```
module_name: uLanding Radar
serial_config:
    - command: ulanding_radar start ${SERIAL_DEV}
      port_config_param:
        name: SENS_ULAND_CFG
        group: Sensors
```
to
```
module_name: uLanding Radar
serial_config:
    - command: ulanding_radar start -d ${SERIAL_DEV}
      port_config_param:
        name: SENS_ULAND_CFG
        group: Sensors
```

I spent a few minutes trying to track down when this issue emerged via blames, but I couldn't track it down.

If someone tells me I'm not crazy I'll make a PR.
