### ISSUE TITLE
px4_sitl_rtps doesn't work with px4_ros_com micrortps_bridge

### ISSUE THREAD

**Issue by jaredsjohansen** [PX4/PX4-Autopilot#19917]
## Describe the bug
In the `master` branch of this repo (from about a month ago), I could follow the steps described [here](https://docs.px4.io/v1.12/en/ros/ros2_comm.html#build-ros-2-workspace) to get data from the `px4_sitl_rtps gazebo` simulator to cross the micrortps bridge and show up in ROS2.  I could also run the offboard_mode example with ROS2.
Around July 8, the `master` branch of this repo was merged into `main`.  When that occurred, data from the `px4_sitl_rtps gazebo` simulator would be sent over the micrortps bridge, but the micrortps_agent would die with this error:
```
terminate called after throwing an instance of 'eprosima::fastcdr::exception::BadParamException'
  what():  Unexpected byte value in Cdr::deserialize(bool), expected 0 or 1
Aborted (core dumped)
```
I believe the bug is associated with this [issue/fix](https://github.com/PX4/PX4-Autopilot/pull/12025), which was made on the `master` branch, but doesn't appear to be fully integrated into the `main` branch.  The first file seems fine.  The second file doesn't.  I tried editing the second file associated with this [MR](https://github.com/PX4/PX4-Autopilot/pull/12025/files) (which appears to be renamed slightly to `msg/templates/uorb_microcdr/msg.cpp.em`), but was unable to get it to work.

When I revert the repo to an earlier version (i.e., right before the `master` -> `main` merge by using `git checkout 10a2b4c9f7d34234459b4d3604b99a33491a9d83`), everything works properly (i.e., data is sent over the micrortps bridge, the micrortps_agent receives it, and you can `ros2 topic echo` any of the messages).

I have checked whether the `px4_msgs` or `px4_ros_com` repos have changed in the previous month.  They have not.  The source of the miscommunication across the micrortps bridge appears to be associated with recent changes to the PX4-Autopilot repo.

## To Reproduce
1. In terminal 1, get the latest version of this repo and start the simulator:
    ```
    git clone https://github.com/PX4/PX4-Autopilot --recursive
    cd ~/PX4-Autopilot
    make
    make px4_sitl_rtps
    make px4_sitl_rtps gazebo
    ```
2. In terminal 2, follow the steps described [here](https://docs.px4.io/v1.12/en/ros/ros2_comm.html#build-ros-2-workspace) to install Fast-DDS, ROS2, and the px4_ros_com_ros2 workspace.  When running the [sanity check the installation](https://docs.px4.io/v1.12/en/ros/ros2_comm.html#sanity-check-the-installation) section, you will run these commands:
    ```
    source ~/px4_ros_com_ros2/install/setup.bash
    micrortps_agent -t UDP
    ```
    which will produce this error:
    ```
    terminate called after throwing an instance of 'eprosima::fastcdr::exception::BadParamException'
      what():  Unexpected byte value in Cdr::deserialize(bool), expected 0 or 1
    Aborted (core dumped)
    ```
3. In terminal 1, revert the PX4-Autopilot to an earlier version and restart the simulator:
    ```
    cd ~/PX4-Autopilot
    git checkout 10a2b4c9f7d34234459b4d3604b99a33491a9d83
    make
    make px4_sitl_rtps
    make px4_sitl_rtps gazebo
    ```
4. In terminal 2, restart the micrortps_agent (`micrortps_agent -t UDP`).  It should not die.
6. In terminal 3, you can now `ros2 topic echo` any of the fields and it will print out data: 
    ```
    ros2 topic echo /fmu/sensor_combined/out
    ---
    timestamp: 1657838030351792
    gyro_rad:
    - -0.0005326324608176947
    - -0.0007989492150954902
    - -0.0007989475270733237
    gyro_integral_dt: 4000
    accelerometer_timestamp_relative: 0
    accelerometer_m_s2:
    - 0.06823474913835526
    - 0.07062912732362747
    - -9.889251708984375
    accelerometer_integral_dt: 4000
    accelerometer_clipping: 0
    gyro_clipping: 0
    accel_calibration_count: 0
    gyro_calibration_count: 1
    ```

## Expected behavior
There should be no error when performing step 2 above.

## Log Files and Screenshots
N/A

## Drone:
px4_sitl_rtps (iris rtps)

## Additional context
None
