### ISSUE TITLE
PX4 in Kubernetes

### ISSUE THREAD

**Issue by akontsevich** [PX4/PX4-Autopilot#20973]
Good article exists [PX4 Docker Containers](https://docs.px4.io/main/en/test_and_ci/docker.html) and it works fine for us. But what if we need to run many simulators simultaneously, for example in kubernetes? Have anybody did something similar? How to  setup cluster and network forwarding in this case? Any solution or suggestions? Thanks!

**Comment by akontsevich** [comment]
On minikube was able to run it only with `hostNetwork: true` in POD settings.

On GKE works with `LoadBalancer` service like mentioned [here](https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing) with 2 opened UDP ports:
```
apiVersion: v1
kind: Service
metadata:
  name: px4-service
spec:
  type: LoadBalancer
  ports:
    - port: 14550
      targetPort: 14550
      protocol: UDP
      name: port14550
    - port: 18570
      targetPort: 18570
      protocol: UDP
      name: port18570
```

However this bug https://github.com/PX4/PX4-Autopilot/issues/20696 prevents from flying.
