### ISSUE TITLE
[Bug] xacro and PX4 autopilot is loaded but QGC is not connected

### ISSUE THREAD

**Issue by crazy-robotics** [PX4/PX4-Autopilot#24510]
### Describe the bug

I am working on indoor drones GPS denied environment so I am using `moveit` by which I give the desired path the drone will follow. Path calculation is done by `moveit` and it publishes on `/mavros/setpoint_position/local` which feeds to `PX4` via `mavros`

[![moveit PX4][1]][1]

I am using following tutorial [Dronedoc][2] [Github][3] and launch 
```
roslaunch dronedoc iris_moveit_1.launch
```

`Gazebo` `PX4 Autopilot` and `Moveit` is launched below I attached the screenshot 
[![enter image description here][4]][4]

[![enter image description here][5]][5]

[![enter image description here][6]][6]

When the path is planned and it will publish on `/mavros/setpoint_position/local` but when I check `/mavros/state` it always shows not connected due to which I can not run my custom ros code. I check `/opt/ros/noetic/share/mavros/launch/px4.launch` `fcu` which is set for SITL. QGC get connected sometime but majority of time it is disconnected
```
<arg name="fcu_url" default="udp://:14540@localhost:14557" />
```

```
mubashir@mubashir:~$ rostopic echo /mavros/state
header: 
  seq: 0
  stamp: 
    secs: 80
    nsecs: 264000000
  frame_id: ''
connected: False
armed: False
guided: False
manual_input: False
mode: ''
system_status: 0
---

```
My setup environment 
`Ubuntu 20.04LTS`
`PX4 V 1.15.2`
`Gazebo classic 11.15.1`
`Moveit 1`
`Qground Control 4.4.3`

  [1]: https://i.sstatic.net/G9U4mQEu.png
  [2]: https://uenota.github.io/dronedoc/ja/index.html
  [3]: https://github.com/crazy-robotics/dronedoc
  [4]: https://i.sstatic.net/QlDbqZnZ.png
  [5]: https://i.sstatic.net/oThEgbmA.png
  [6]: https://i.sstatic.net/UoHUHJED.png

### Screenshot / Media

added

### Flight Log

NA

### Vehicle type

None
